export const FETCH_TOP_SALES_REQUEST = 'FETCH_TOP_SALES_REQUEST';
export const FETCH_TOP_SALES_FAILURE = 'FETCH_TOP_SALES_FAILURE';
export const FETCH_TOP_SALES_SUCCESS = 'FETCH_TOP_SALES_SUCCESS';
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_ALL_ITEMS_REQUEST = 'FETCH_ALL_ITEMS_REQUEST';
export const FETCH_ALL_ITEMS_FAILURE = 'FETCH_ALL_ITEMS_FAILURE';
export const FETCH_ALL_ITEMS_SUCCESS = 'FETCH_ALL_ITEMS_SUCCESS';
export const FETCH_SELECTED_CATEGORY_ITEMS_REQUEST =
  'FETCH_SELECTED_CATEGORY_ITEMS_REQUEST';
export const FETCH_SELECTED_CATEGORY_ITEMS_FAILURE =
  'FETCH_SELECTED_CATEGORY_ITEMS_FAILURE';
export const FETCH_SELECTED_CATEGORY_ITEMS_SUCCESS =
  'FETCH_SELECTED_CATEGORY_ITEMS_SUCCESS';
